'use client';
import { ExamplesMenu } from '@/components/ExamplesMenu';
import { FlameLoader } from '@/components/FlameLoader';
import { Navigator } from '@/components/Navigator';
import { FireFist } from '@/components/FireFist';
import TXT from '@/lib/strings';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>SUPERLIB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FlameLoader mode="fullpage" greeting />
      <ExamplesMenu />
      <main className="bg-PAPER h-[100vh] px-4 dark:bg-IRON md:px-20 lg:px-40">
        <Navigator />
        <section className="justify-center h-auto mb-16 lg:mb-0 group rounded-lg border p-2 transition-colors text-IRON dark:text-PAPER border-gray-400/30 bg-gray-100/30 dark:border-neutral-700 dark:bg-neutral-800/30">
          <div className="flex flex-col md:flex-row w-full justify-center items-center gap-4 select-none">
            <FireFist mode="hand" size="sm" />
            <p className="mt-4 md:mt-16 text-transparent opacity-70 bg-clip-text bg-gradient-to-r from-ROSE to-ORANGE dark:from-CYAN dark:to-EMERALD font-burtons text-5xl md:text-6xl lg:text-7xl border-b-4 border-ROSE/50 dark:border-CYAN/50">
              {TXT('FRONTEND_IS_ART')}
            </p>
          </div>
          <p className="opacity-90 text-IRON dark:text-PAPER p-2 md:p-4 md:pt-16 font-jubilat text-lg md:text-xl lg:text-2xl text-justify">
            {TXT('INTRO1')}
          </p>
          <p className="opacity-90 text-IRON dark:text-PAPER p-2 pt-1 md:px-4 font-jubilat text-lg md:text-xl lg:text-2xl text-justify">
            {TXT('INTRO2')}
          </p>
          <p className="opacity-90 text-IRON dark:text-PAPER p-2 pt-1 md:px-4 font-jubilat text-lg md:text-xl lg:text-2xl text-end">
            {TXT('INTRO3')}
          </p>
        </section>
      </main>
    </>
  );
}
