'use client';
import { Navigator } from '@/components/Navigator';
import Head from 'next/head';
export default function Home() {
  return (
    <>
      <Head>
        <title>SUPERLIB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-PAPER h-[100vh] px-4 dark:bg-IRON md:px-20 lg:px-40">
        <Navigator />

        <div className="mb-16 text-center lg:w-full lg:mb-0 lg:text-left">
          <section className="group rounded-lg border border-transparent px-5 py-4 text-center transition-colors border-gray-300 bg-gray-100 dark:border-neutral-700 dark:bg-neutral-800/30">
            <h2 className={`mb-3 text-2xl font-semibold`}>
              Docs{' '}
              <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
                -&gt;
              </span>
            </h2>
          </section>
        </div>
      </main>
    </>
  );
}
